server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/product_db
    username: postgres
    password: Kvlv!@135

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
